#PG - aula 5 - try.py

for _ in range(50):
    print("Funcionando")
    
try:    
    resultado = 2/0
    print("O resultado da divisão é: ")
except ZeroDivisionError:    
    

